services:
  - name: yintii
    type: web
    env: ruby
    buildCommand: bin/render-build.sh 
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: yintii-db
          property: connectionString

databases:
  - name: yintii-db
    ipAllowList: []
